### ISSUE TITLE
Any plan to release a Scala 2.12/Play 2.6/Silhouette 5.0.0 compatible version?

### ISSUE THREAD

**Issue by epot** [mohiva/play-silhouette-persistence-reactivemongo#11]
Hello,

My bad if this is documented somewhere, but are there any plan to depend on the new Play 2.6 and Silhouette 5.0.0 (still in RC)?

Thanks!
Emmanuel

**Comment by akkie** [comment]
I'm working on this. If this fix for [play2-reactivemongo](https://groups.google.com/forum/#!topic/reactivemongo/dMHOjpl1mR8) works, then I'll release a Play 2.6 compatible version.

**Comment by epot** [comment]
Awesome, thanks!

**Comment by akkie** [comment]
I've just released 5.0.0-RC1
